//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKSOFDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen_FollowUps
    {
        public Citizen_FollowUps()
        {
            this.Citizen_Notes1 = new HashSet<Citizen_Notes>();
            this.Documents = new HashSet<Document>();
        }
    
        public System.Guid GUID { get; set; }
        public System.DateTime Createdtimestamp { get; set; }
        public System.DateTime Log_from { get; set; }
        public System.Guid Log_UserId { get; set; }
        public System.Guid CitizenId { get; set; }
        public Nullable<System.DateTime> NextFollowupdate { get; set; }
        public string Description { get; set; }
        public string Consent { get; set; }
        public string CaseWorkerdescription { get; set; }
        public System.Guid StatusNoteID { get; set; }
        public Nullable<byte> Result { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Security_Citizens Security_Citizens { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Citizen_Notes Citizen_Notes { get; set; }
        public virtual ICollection<Citizen_Notes> Citizen_Notes1 { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
