//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKSOFDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenstatusNoteMapping
    {
        public System.Guid GUID { get; set; }
        public System.Guid StatusNoteId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Citizen_Notes Citizen_Notes { get; set; }
        public virtual Security_User Security_User { get; set; }
    }
}
