//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKSOFDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen_FollowUpAttachments
    {
        public System.Guid GUID { get; set; }
        public System.DateTime Createdtimestamp { get; set; }
        public Nullable<System.Guid> Log_UserId { get; set; }
        public Nullable<System.Guid> CitizenId { get; set; }
        public string DocType { get; set; }
        public string Docname { get; set; }
        public Nullable<System.Guid> Objectid { get; set; }
        public System.Guid FollowupId { get; set; }
    }
}
