//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKSOFDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid GUID { get; set; }
        public System.DateTime Createdtimestamp { get; set; }
        public System.DateTime Log_from { get; set; }
        public System.Guid Log_UserId { get; set; }
        public byte DocumentType { get; set; }
        public string Name { get; set; }
        public string DocURL { get; set; }
        public Nullable<System.Guid> FollowupID { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CitizenId { get; set; }
    
        public virtual Citizen_FollowUps Citizen_FollowUps { get; set; }
        public virtual Security_Citizens Security_Citizens { get; set; }
        public virtual Security_User Security_User { get; set; }
    }
}
