//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKSOFDemoApp.Models
{
    using System;
    
    public partial class GET_CITIZENS_Result1
    {
        public System.Guid GUID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string PersonalIdNo { get; set; }
        public byte Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public System.DateTime Dateofbirth { get; set; }
        public string Profession { get; set; }
    }
}
